In [1]:
import pandas as pd
import numpy as np

# Importing X company data and analyzing it.

In [2]:
X_COD = pd.read_excel("K:\Major project\cointab\Assignment details\\X-Order Report.xlsx")
X_COD.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ExternOrderNo         400 non-null    int64
 1   SKU                   400 non-null    object
 2   Order Qty             400 non-null    int64
 3   Payment Mode          400 non-null    object
 4   Item Price(Per Qty.)  400 non-null    int64
dtypes: int64(3), object(2)
memory usage: 15.8+ KB

In [3]:
X_COD["Total Order Price (rs.)"] = X_COD["Order Qty"]*X_COD["Item Price(Per Qty.)"]
X_COD.head()

,ExternOrderNo,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),Total Order Price (rs.)
0,2001827036,8904223818706,1,COD,233,233
1,2001827036,8904223819093,1,COD,233,233
2,2001827036,8904223819109,1,COD,233,233
3,2001827036,8904223818430,1,COD,470,470
4,2001827036,8904223819277,1,COD,233,233

In [4]:
#Calculating COD charge.

charge = []
for x in X_COD["Payment Mode"]:
    if x == "COD":
        for y in X_COD["Total Order Price (rs.)"]:
        
            if y<=300:
                charge.append(15)
            else:
                charge.append(y*0.05)
    else:
        charge.append(0)
charge[0:400]

[15,
 15,
 15,
 23.5,
 15,
 32.95,
 57.0,
 17.5,
 727.2,
 781.4000000000001,
 128.25,
 15.05,
 17.5,
 195.4,
 103.10000000000001,
 181.8,
 120.5,
 3125.6000000000004,
 15,
 15,
 47.300000000000004,
 28.150000000000002,
 23.5,
 15,
 30.150000000000002,
 23.5,
 29.1,
 103.10000000000001,
 181.8,
 15.100000000000001,
 45.45,
 38.85,
 22.400000000000002,
 57.1,
 199.8,
 15,
 15,
 33.4,
 15.05,
 15,
 28.150000000000002,
 47.550000000000004,
 15,
 20.150000000000002,
 15,
 15,
 17.5,
 15,
 186.4,
 49.95,
 31.3,
 43.25,
 20.1,
 46.1,
 26.700000000000003,
 40.95,
 195.4,
 103.10000000000001,
 181.8,
 16.1,
 15,
 15,
 28.150000000000002,
 80.4,
 184.3,
 186.4,
 53.1,
 15,
 20.1,
 46.1,
 15,
 20.1,
 46.1,
 15,
 15,
 28.150000000000002,
 15,
 15,
 28.150000000000002,
 31.3,
 15,
 15,
 43.25,
 35.050000000000004,
 195.4,
 103.10000000000001,
 181.8,
 29.1,
 412.20000000000005,
 412.20000000000005,
 30.1,
 15,
 15,
 28.150000000000002,
 15,
 15,
 28.150000000000002,
 20.1,
 60.2,
 49.95,
 15,
 15.05,
 48.0,
 25.8,
 15,
 28.150000000000002,
 30.150000000000002,
 47.550000000000004,
 47.400000000000006,
 15,
 47.550000000000004,
 38.050000000000004,
 32.65,
 15,
 30.150000000000002,
 20.1,
 48.0,
 17.5,
 26.700000000000003,
 30.150000000000002,
 23.950000000000003,
 46.1,
 20.1,
 46.1,
 40.95,
 195.4,
 103.10000000000001,
 181.8,
 15,
 28.150000000000002,
 30.150000000000002,
 15,
 15,
 28.150000000000002,
 15,
 49.95,
 28.150000000000002,
 15,
 28.150000000000002,
 30.150000000000002,
 30.150000000000002,
 39.300000000000004,
 15.05,
 57.0,
 15,
 15,
 28.150000000000002,
 15,
 15,
 28.150000000000002,
 28.150000000000002,
 49.95,
 30.150000000000002,
 28.150000000000002,
 49.95,
 48.0,
 17.5,
 26.700000000000003,
 15,
 31.3,
 43.25,
 15,
 103.10000000000001,
 181.8,
 20.1,
 46.1,
 40.95,
 28.700000000000003,
 15,
 15,
 28.150000000000002,
 39.300000000000004,
 43.25,
 38.050000000000004,
 15,
 20.1,
 39.300000000000004,
 36.45,
 45.800000000000004,
 15,
 2908.4,
 199.8,
 28.150000000000002,
 15,
 28.150000000000002,
 30.150000000000002,
 15,
 15,
 28.150000000000002,
 15,
 15,
 28.150000000000002,
 15,
 15,
 28.150000000000002,
 15,
 15,
 28.150000000000002,
 22.400000000000002,
 80.60000000000001,
 148.1,
 47.550000000000004,
 48.25,
 20.1,
 46.1,
 15,
 15,
 28.150000000000002,
 15.100000000000001,
 37.050000000000004,
 47.550000000000004,
 28.3,
 17.5,
 31.75,
 15,
 15,
 28.150000000000002,
 120.5,
 46.6,
 15,
 28.150000000000002,
 30.150000000000002,
 15,
 15,
 28.150000000000002,
 40.5,
 33.800000000000004,
 49.95,
 30.150000000000002,
 28.150000000000002,
 15,
 28.150000000000002,
 30.150000000000002,
 47.550000000000004,
 20.150000000000002,
 47.400000000000006,
 195.4,
 103.10000000000001,
 181.8,
 40.5,
 33.800000000000004,
 30.150000000000002,
 15,
 15,
 28.150000000000002,
 30.150000000000002,
 15.05,
 49.95,
 15,
 38.85,
 23.5,
 15.05,
 15,
 28.150000000000002,
 17.5,
 15,
 15,
 28.150000000000002,
 44.400000000000006,
 15,
 28.150000000000002,
 30.150000000000002,
 30.150000000000002,
 15,
 15,
 28.150000000000002,
 15,
 28.150000000000002,
 30.150000000000002,
 15,
 15,
 28.150000000000002,
 15,
 30.150000000000002,
 15,
 112.5,
 15,
 727.2,
 927.3000000000001,
 1636.2,
 195.4,
 103.10000000000001,
 181.8,
 15,
 15,
 28.150000000000002,
 15,
 15,
 15,
 28.150000000000002,
 15,
 28.150000000000002,
 30.150000000000002,
 15,
 15,
 28.150000000000002,
 15,
 15,
 28.150000000000002,
 15,
 15,
 33.4,
 15,
 20.150000000000002,
 47.400000000000006,
 781.4000000000001,
 412.20000000000005,
 727.2,
 30.1,
 30.150000000000002,
 15,
 15,
 28.150000000000002,
 15,
 15,
 28.150000000000002,
 192.0,
 192.0,
 15,
 15,
 28.150000000000002,
 15,
 28.150000000000002,
 49.95,
 15,
 57.0,
 17.5,
 426.6,
 15,
 15,
 28.150000000000002,
 25.8,
 23.5,
 28.150000000000002,
 26.700000000000003,
 30.150000000000002,
 15,
 15,
 28.150000000000002,
 30.150000000000002,
 15,
 15,
 28.150000000000002,
 15.05,
 49.95,
 15,
 15,
 45.45,
 22.1,
 15,
 15,
 28.150000000000002,
 15,
 20.1,
 45.45,
 33.4,
 41.7,
 47.300000000000004,
 15,
 15,
 15,
 28.150000000000002,
 46.6,
 57.1,
 112.5,
 15,
 15,
 28.150000000000002,
 49.95,
 43.25,
 31.3,
 15,
 15,
 28.150000000000002,
 184.3,
 38.050000000000004,
 2908.4,
 46.1,
 15,
 15,
 28.150000000000002,
 15,
 15,
 28.150000000000002,
 30.1,
 15,
 15,
 28.150000000000002,
 40.5,
 33.800000000000004,
 40.5,
 33.800000000000004,
 501.90000000000003,
 46.6,
 15,
 15,
 28.150000000000002,
 112.5,
 20.1,
 46.1]

In [5]:
X_COD["COD Charge (Rs.)"] = charge[0:400]
X_COD["COD Charge (Rs.)"] = np.where(X_COD["Payment Mode"]=='Prepaid', 0 ,X_COD["COD Charge (Rs.)"] )
X_COD.head(10)

,ExternOrderNo,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),Total Order Price (rs.),COD Charge (Rs.)
0,2001827036,8904223818706,1,COD,233,233,15.00
1,2001827036,8904223819093,1,COD,233,233,15.00
2,2001827036,8904223819109,1,COD,233,233,15.00
3,2001827036,8904223818430,1,COD,470,470,23.50
4,2001827036,8904223819277,1,COD,233,233,15.00
5,2001827036,GIFTBOX202002,1,COD,659,659,32.95
6,2001827036,8904223818638,2,COD,570,1140,57.00
7,2001827036,SACHETS001,1,COD,350,350,17.50
8,2001825261,8904223819024,4,Prepaid,3636,14544,0.00
9,2001825261,8904223819291,4,Prepaid,3907,15628,0.00

In [6]:
X_COD.shape

(400, 7)

In [7]:
X_COD.rename(columns = {"ExternOrderNo":"Order ID"} , inplace = True)

In [8]:
#Importing weight table.

X_weight = pd.read_excel("K:\Major project\cointab\Assignment details\\X-weight.xlsx")
X_weight.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SKU         66 non-null     object
 1   Weight (g)  66 non-null     int64
dtypes: int64(1), object(1)
memory usage: 1.2+ KB

In [9]:
#conerting weight in gms to KG
X_weight["Weight (g)"] = X_weight["Weight (g)"]/1000

In [10]:
X_weight.rename(columns = {"Weight (g)":"Total weight as per X (KG)"} , inplace = True)
X_weight.head(10)

             SKU  Total weight as per X (KG)
0  8904223815682                       0.210
1  8904223815859                       0.165
2  8904223815866                       0.113
3  8904223815873                       0.065
4  8904223816214                       0.120
5  8904223816665                       0.102
6  8904223817273                       0.065
7  8904223817334                       0.170
8  8904223817501                       0.350
9  8904223818430                       0.165

In [11]:
X_comp = pd.merge(X_COD, X_weight , on= "SKU")
X_comp.head()

,Order ID,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),Total Order Price (rs.),COD Charge (Rs.),Total weight as per X (KG)
0,2001827036,8904223818706,1,COD,233,233,15.0,0.127
1,2001821995,8904223818706,1,Prepaid,233,233,0.0,0.127
2,2001819252,8904223818706,1,Prepaid,233,233,0.0,0.127
3,2001816996,8904223818706,1,Prepaid,233,233,0.0,0.127
4,2001814580,8904223818706,1,COD,233,233,15.0,0.127

In [12]:
X_comp.shape

(401, 8)

# Importing courier data and merging to X company data.

In [13]:
courier = pd.read_excel("K:\Major project\cointab\Assignment details\\Courier-Invoice.xlsx")

In [14]:
X_zone = pd.read_excel("K:\Major project\cointab\Assignment details\\X-Zones.xlsx")

In [15]:
courier.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124 entries, 0 to 123
Data columns (total 8 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   AWB Code                                  124 non-null    int64
 1   Order ID                                  124 non-null    int64
 2   Charged Weight                            124 non-null    float64
 3   Warehouse Pincode                         124 non-null    int64
 4   Customer Pincode                          124 non-null    int64
 5   Delivery Zone charged by Courier Company  124 non-null    object
 6   Type of Shipment                          124 non-null    object
 7   Billing Amount (Rs.)                      124 non-null    float64
dtypes: float64(2), int64(4), object(2)
memory usage: 7.9+ KB

In [16]:
df = courier.merge(X_zone , on = ["Warehouse Pincode","Customer Pincode"])
df.shape

(174, 9)

In [17]:
df.head()

,AWB Code,Order ID,Charged Weight,Warehouse Pincode,Customer Pincode,Delivery Zone charged by Courier Company,Type of Shipment,Billing Amount (Rs.),Delivery Zone as per X
0,1091117222124,2001806232,1.30,121003,507101,d,Forward charges,140.0,d
1,1091117222194,2001806273,1.00,121003,486886,d,Forward charges,101.2,d
2,1091117222931,2001806408,2.50,121003,532484,d,Forward charges,224.6,d
3,1091117223244,2001806458,1.00,121003,143001,b,Forward charges,61.3,b
4,1091117229345,2001807012,0.15,121003,515591,d,Forward charges,45.4,d

In [18]:
data = df.merge(X_comp , on = 'Order ID')
data.shape

(567, 16)

In [19]:
data.head()

,AWB Code,Order ID,Charged Weight,Warehouse Pincode,Customer Pincode,Delivery Zone charged by Courier Company,Type of Shipment,Billing Amount (Rs.),Delivery Zone as per X,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),Total Order Price (rs.),COD Charge (Rs.),Total weight as per X (KG)
0,1091117222124,2001806232,1.3,121003,507101,d,Forward charges,140.0,d,8904223819147,2,COD,466,932,46.60,0.240
1,1091117222124,2001806232,1.3,121003,507101,d,Forward charges,140.0,d,8904223818645,6,COD,1673,10038,501.90,0.137
2,1091117222194,2001806273,1.0,121003,486886,d,Forward charges,101.2,d,8904223818706,1,COD,233,233,15.00,0.127
3,1091117222194,2001806273,1.0,121003,486886,d,Forward charges,101.2,d,8904223818850,1,COD,563,563,28.15,0.240
4,1091117222194,2001806273,1.0,121003,486886,d,Forward charges,101.2,d,8904223818942,1,COD,286,286,15.00,0.133

In [21]:
data = data.drop(columns=["Warehouse Pincode", "Customer Pincode", "SKU","Order Qty", "Item Price(Per Qty.)"])

In [22]:
data.head()

,AWB Code,Order ID,Charged Weight,Delivery Zone charged by Courier Company,Type of Shipment,Billing Amount (Rs.),Delivery Zone as per X,Payment Mode,Total Order Price (rs.),COD Charge (Rs.),Total weight as per X (KG)
0,1091117222124,2001806232,1.3,d,Forward charges,140.0,d,COD,932,46.60,0.240
1,1091117222124,2001806232,1.3,d,Forward charges,140.0,d,COD,10038,501.90,0.137
2,1091117222194,2001806273,1.0,d,Forward charges,101.2,d,COD,233,15.00,0.127
3,1091117222194,2001806273,1.0,d,Forward charges,101.2,d,COD,563,28.15,0.240
4,1091117222194,2001806273,1.0,d,Forward charges,101.2,d,COD,286,15.00,0.133

In [23]:
data.rename(columns= {"Charged Weight":"Total weight as per Courier Company (KG)"}, inplace = True)

In [24]:
data.rename(columns= {"Billing Amount (Rs.)":"Charges Billed by Courier Company (Rs.)"}, inplace = True)

In [25]:
data1 = data.drop_duplicates()

In [26]:
data1.shape

(398, 11)

In [27]:
data1["Delivery Zone as per X"].unique()

array(['d', 'b', 'e'], dtype=object)

# Calculating Weight slab as per X, according to different zone.

In [28]:
Xzone_b = data1[data1["Delivery Zone as per X"] == 'b']

In [29]:
Xzone_b.shape

(236, 11)

In [30]:
Xzone_d = data1[data1["Delivery Zone as per X"] == 'd']

In [31]:
Xzone_d.shape

(136, 11)

In [32]:
Xzone_e = data1[data1["Delivery Zone as per X"] == 'e']
Xzone_e.shape

(26, 11)

In [34]:
#Weight slab as per X for b zone.

def weight_slab(weight):
    i = round(weight % 1, 1)
    if i == 0.0:
        return weight
    elif i > 0.5:
        return int(weight)+1
    else:
        return int(weight)+0.5
    
Xzone_b["Weight slab as per X (KG)"] = Xzone_b["Total weight as per X (KG)"].apply(weight_slab)
Xzone_b.head()

C:\Users\kusha\AppData\Local\Temp\ipykernel_9592\172714460.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Xzone_b["Weight slab as per X (KG)"] = Xzone_b["Total weight as per X (KG)"].apply(weight_slab)

,AWB Code,Order ID,Total weight as per Courier Company (KG),Delivery Zone charged by Courier Company,Type of Shipment,Charges Billed by Courier Company (Rs.),Delivery Zone as per X,Payment Mode,Total Order Price (rs.),COD Charge (Rs.),Total weight as per X (KG),Weight slab as per X (KG)
10,1091117223244,2001806458,1.00,b,Forward charges,61.3,b,Prepaid,626,0.0,0.35,0.5
11,1091117223244,2001806458,1.00,b,Forward charges,61.3,b,Prepaid,865,0.0,0.35,0.5
14,1091117229776,2001806885,1.00,b,Forward charges,61.3,b,COD,3840,192.0,0.21,0.5
16,1091117323112,2001807058,1.15,b,Forward charges,89.6,b,Prepaid,233,0.0,0.29,0.5
17,1091117323112,2001807058,1.15,b,Forward charges,89.6,b,Prepaid,222,0.0,0.29,0.5

In [35]:
#Weight slab as per X for d zone.

def weight_slab(weight):
    i = round(weight % 1.25, 2)
    if i == 0.00:
        return weight
    elif weight<1.25:
        return 1.25 
    else: 
        return (weight//1.25)*1.25+1.25
    
Xzone_d["Weight slab as per X (KG)"] = Xzone_d["Total weight as per X (KG)"].apply(weight_slab)
Xzone_d.head()

C:\Users\kusha\AppData\Local\Temp\ipykernel_9592\2282394578.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Xzone_d["Weight slab as per X (KG)"] = Xzone_d["Total weight as per X (KG)"].apply(weight_slab)

,AWB Code,Order ID,Total weight as per Courier Company (KG),Delivery Zone charged by Courier Company,Type of Shipment,Charges Billed by Courier Company (Rs.),Delivery Zone as per X,Payment Mode,Total Order Price (rs.),COD Charge (Rs.),Total weight as per X (KG),Weight slab as per X (KG)
0,1091117222124,2001806232,1.3,d,Forward charges,140.0,d,COD,932,46.60,0.240,1.25
1,1091117222124,2001806232,1.3,d,Forward charges,140.0,d,COD,10038,501.90,0.137,1.25
2,1091117222194,2001806273,1.0,d,Forward charges,101.2,d,COD,233,15.00,0.127,1.25
3,1091117222194,2001806273,1.0,d,Forward charges,101.2,d,COD,563,28.15,0.240,1.25
4,1091117222194,2001806273,1.0,d,Forward charges,101.2,d,COD,286,15.00,0.133,1.25

In [36]:
#Weight slab as per X for e zone.

def weight_slab(weight):
    i = round(weight % 1.5, 2)
    if i == 0.00:
        return weight
    elif weight<1.5:
        return 1.55 
    else: 
        return (weight//1.5)*1.5+1.5
    
Xzone_e["Weight slab as per X (KG)"] = Xzone_e["Total weight as per X (KG)"].apply(weight_slab)
Xzone_e.head()

C:\Users\kusha\AppData\Local\Temp\ipykernel_9592\4051937626.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Xzone_e["Weight slab as per X (KG)"] = Xzone_e["Total weight as per X (KG)"].apply(weight_slab)

,AWB Code,Order ID,Total weight as per Courier Company (KG),Delivery Zone charged by Courier Company,Type of Shipment,Charges Billed by Courier Company (Rs.),Delivery Zone as per X,Payment Mode,Total Order Price (rs.),COD Charge (Rs.),Total weight as per X (KG),Weight slab as per X (KG)
64,1091117435661,2001808295,0.2,e,Forward and RTO charges,127.3,e,COD,810,40.50,0.115,1.55
65,1091117435661,2001808295,0.2,e,Forward and RTO charges,127.3,e,COD,676,33.80,0.130,1.55
88,1091120014461,2001818390,0.8,e,Forward and RTO charges,213.5,e,COD,999,49.95,0.121,1.55
89,1091120014461,2001818390,0.8,e,Forward and RTO charges,213.5,e,COD,233,15.00,0.240,1.55
90,1091120014461,2001818390,0.8,e,Forward and RTO charges,213.5,e,COD,3728,186.40,0.120,1.55

# Calculating Expected charge as per X, according to different zone.

In [37]:
#Expected charge as per X for b zone.

fwd_fixed = 33
fwd_additional = 28.3
rto_fixed = 20.5
rto_additional = 28.3
weight_slab = Xzone_b["Weight slab as per X (KG)"]
additional_weight = (weight_slab - 0.5)/0.5
Xzone_b['Expected Charge as per X (Rs.)'] = 0
Xzone_b['Expected Charge as per X (Rs.)']= np.where(Xzone_b['Type of Shipment'] == 'Forward charges', (fwd_fixed + additional_weight * fwd_additional) ,Xzone_b['Expected Charge as per X (Rs.)'] )
Xzone_b['Expected Charge as per X (Rs.)']= np.where(Xzone_b['Type of Shipment'] == 'Forward and RTO charges', (fwd_fixed + rto_fixed + additional_weight * (fwd_additional + rto_additional)) ,Xzone_b['Expected Charge as per X (Rs.)'] )
Xzone_b.head()

C:\Users\kusha\AppData\Local\Temp\ipykernel_9592\2900443754.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Xzone_b['Expected Charge as per X (Rs.)'] = 0
C:\Users\kusha\AppData\Local\Temp\ipykernel_9592\2900443754.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Xzone_b['Expected Charge as per X (Rs.)']= np.where(Xzone_b['Type of Shipment'] == 'Forward charges', (fwd_fixed + additional_weight * fwd_additional) ,Xzone_b['Expected Charge as per X (Rs.)'] )
C:\Users\kusha\AppData\Local\Temp\ipykernel_9592\2900443754.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Xzone_b['Expected Charge as per X (Rs.)']= np.where(Xzone_b['Type of Shipment'] == 'Forward and RTO charges', (fwd_fixed + rto_fixed + additional_weight * (fwd_additional + rto_additional)) ,Xzone_b['Expected Charge as per X (Rs.)'] )

,AWB Code,Order ID,Total weight as per Courier Company (KG),Delivery Zone charged by Courier Company,Type of Shipment,Charges Billed by Courier Company (Rs.),Delivery Zone as per X,Payment Mode,Total Order Price (rs.),COD Charge (Rs.),Total weight as per X (KG),Weight slab as per X (KG),Expected Charge as per X (Rs.)
10,1091117223244,2001806458,1.00,b,Forward charges,61.3,b,Prepaid,626,0.0,0.35,0.5,33.0
11,1091117223244,2001806458,1.00,b,Forward charges,61.3,b,Prepaid,865,0.0,0.35,0.5,33.0
14,1091117229776,2001806885,1.00,b,Forward charges,61.3,b,COD,3840,192.0,0.21,0.5,33.0
16,1091117323112,2001807058,1.15,b,Forward charges,89.6,b,Prepaid,233,0.0,0.29,0.5,33.0
17,1091117323112,2001807058,1.15,b,Forward charges,89.6,b,Prepaid,222,0.0,0.29,0.5,33.0

In [38]:
#Expected charge as per X for d zone.

fwd_fixed = 45.4
fwd_additional = 44.8
rto_fixed = 41.3
rto_additional = 44.8
weight_slab = Xzone_d["Weight slab as per X (KG)"]
additional_weight = (weight_slab - 1.25)/1.25
Xzone_d['Expected Charge as per X (Rs.)'] = 0
Xzone_d['Expected Charge as per X (Rs.)']= np.where(Xzone_d['Type of Shipment'] == 'Forward charges', (fwd_fixed + additional_weight * fwd_additional) ,Xzone_d['Expected Charge as per X (Rs.)'] )
Xzone_d['Expected Charge as per X (Rs.)']= np.where(Xzone_d['Type of Shipment'] == 'Forward and RTO charges', (fwd_fixed + rto_fixed + additional_weight * (fwd_additional + rto_additional)) ,Xzone_d['Expected Charge as per X (Rs.)'] )
Xzone_d

C:\Users\kusha\AppData\Local\Temp\ipykernel_9592\2968773067.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Xzone_d['Expected Charge as per X (Rs.)'] = 0
C:\Users\kusha\AppData\Local\Temp\ipykernel_9592\2968773067.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Xzone_d['Expected Charge as per X (Rs.)']= np.where(Xzone_d['Type of Shipment'] == 'Forward charges', (fwd_fixed + additional_weight * fwd_additional) ,Xzone_d['Expected Charge as per X (Rs.)'] )
C:\Users\kusha\AppData\Local\Temp\ipykernel_9592\2968773067.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Xzone_d['Expected Charge as per X (Rs.)']= np.where(Xzone_d['Type of Shipment'] == 'Forward and RTO charges', (fwd_fixed + rto_fixed + additional_weight * (fwd_additional + rto_additional)) ,Xzone_d['Expected Charge as per X (Rs.)'] )

,AWB Code,Order ID,Total weight as per Courier Company (KG),Delivery Zone charged by Courier Company,Type of Shipment,Charges Billed by Courier Company (Rs.),Delivery Zone as per X,Payment Mode,Total Order Price (rs.),COD Charge (Rs.),Total weight as per X (KG),Weight slab as per X (KG),Expected Charge as per X (Rs.)
0,1091117222124,2001806232,1.3,d,Forward charges,140.0,d,COD,932,46.60,0.240,1.25,45.4
1,1091117222124,2001806232,1.3,d,Forward charges,140.0,d,COD,10038,501.90,0.137,1.25,45.4
2,1091117222194,2001806273,1.0,d,Forward charges,101.2,d,COD,233,15.00,0.127,1.25,45.4
3,1091117222194,2001806273,1.0,d,Forward charges,101.2,d,COD,563,28.15,0.240,1.25,45.4
4,1091117222194,2001806273,1.0,d,Forward charges,101.2,d,COD,286,15.00,0.133,1.25,45.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,1091117795623,2001809820,3.0,d,Forward charges,269.4,d,Prepaid,402,0.00,0.120,1.25,45.4
216,1091117795623,2001809820,3.0,d,Forward charges,269.4,d,Prepaid,922,0.00,0.100,1.25,45.4
217,1091117795623,2001809820,3.0,d,Forward charges,269.4,d,Prepaid,819,0.00,0.140,1.25,45.4
218,1091117795623,2001809820,3.0,d,Forward charges,269.4,d,Prepaid,786,0.00,0.232,1.25,45.4
219,1091117795623,2001809820,3.0,d,Forward charges,269.4,d,Prepaid,574,0.00,0.140,1.25,45.4

In [39]:
#Expected charge as per X for e zone.

fwd_fixed = 56.6
fwd_additional = 55.5
rto_fixed = 50.7
rto_additional = 55.5
weight_slab = Xzone_e["Weight slab as per X (KG)"]
additional_weight = (weight_slab - 1.5)/1.5
Xzone_e['Expected Charge as per X (Rs.)'] = 0
Xzone_e['Expected Charge as per X (Rs.)']= np.where(Xzone_e['Type of Shipment'] == 'Forward charges', (fwd_fixed + additional_weight * fwd_additional) ,Xzone_e['Expected Charge as per X (Rs.)'] )
Xzone_e['Expected Charge as per X (Rs.)']= np.where(Xzone_e['Type of Shipment'] == 'Forward and RTO charges', (fwd_fixed + rto_fixed + additional_weight * (fwd_additional + rto_additional)) ,Xzone_e['Expected Charge as per X (Rs.)'] )
Xzone_e

C:\Users\kusha\AppData\Local\Temp\ipykernel_9592\3348078540.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Xzone_e['Expected Charge as per X (Rs.)'] = 0
C:\Users\kusha\AppData\Local\Temp\ipykernel_9592\3348078540.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Xzone_e['Expected Charge as per X (Rs.)']= np.where(Xzone_e['Type of Shipment'] == 'Forward charges', (fwd_fixed + additional_weight * fwd_additional) ,Xzone_e['Expected Charge as per X (Rs.)'] )
C:\Users\kusha\AppData\Local\Temp\ipykernel_9592\3348078540.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Xzone_e['Expected Charge as per X (Rs.)']= np.where(Xzone_e['Type of Shipment'] == 'Forward and RTO charges', (fwd_fixed + rto_fixed + additional_weight * (fwd_additional + rto_additional)) ,Xzone_e['Expected Charge as per X (Rs.)'] )

,AWB Code,Order ID,Total weight as per Courier Company (KG),Delivery Zone charged by Courier Company,Type of Shipment,Charges Billed by Courier Company (Rs.),Delivery Zone as per X,Payment Mode,Total Order Price (rs.),COD Charge (Rs.),Total weight as per X (KG),Weight slab as per X (KG),Expected Charge as per X (Rs.)
64,1091117435661,2001808295,0.20,e,Forward and RTO charges,127.3,e,COD,810,40.50,0.115,1.55,111.00
65,1091117435661,2001808295,0.20,e,Forward and RTO charges,127.3,e,COD,676,33.80,0.130,1.55,111.00
88,1091120014461,2001818390,0.80,e,Forward and RTO charges,213.5,e,COD,999,49.95,0.121,1.55,111.00
89,1091120014461,2001818390,0.80,e,Forward and RTO charges,213.5,e,COD,233,15.00,0.240,1.55,111.00
90,1091120014461,2001818390,0.80,e,Forward and RTO charges,213.5,e,COD,3728,186.40,0.120,1.55,111.00
449,1091118004245,2001811604,0.80,b,Forward charges,67.3,e,COD,1204,60.20,0.240,1.55,58.45
450,1091118004245,2001811604,0.80,b,Forward charges,67.3,e,COD,999,49.95,0.121,1.55,58.45
451,1091118004245,2001811604,0.80,b,Forward charges,67.3,e,COD,402,20.10,0.120,1.55,58.45
455,1091121844806,2001811475,0.50,b,Forward charges,47.0,e,COD,233,15.00,0.127,1.55,58.45
456,1091121844806,2001811475,0.50,b,Forward charges,47.0,e,COD,301,15.05,0.240,1.55,58.45
457,1091121844806,2001811475,0.50,b,Forward charges,47.0,e,COD,516,25.80,0.112,1.55,58.45
458,1091121844806,2001811475,0.50,b,Forward charges,47.0,e,COD,960,48.00,0.210,1.55,58.45
463,1091120352712,2001819252,0.30,b,Forward charges,33.0,e,Prepaid,233,0.00,0.127,1.55,58.45
464,1091120352712,2001819252,0.30,b,Forward charges,33.0,e,Prepaid,350,0.00,0.010,1.55,58.45
465,1091120352712,2001819252,0.30,b,Forward charges,33.0,e,Prepaid,286,0.00,0.133,1.55,58.45
466,1091122418320,2001827036,1.60,b,Forward charges,117.9,e,COD,233,15.00,0.127,1.55,58.45
467,1091122418320,2001827036,1.60,b,Forward charges,117.9,e,COD,233,15.00,0.150,1.55,58.45
468,1091122418320,2001827036,1.60,b,Forward charges,117.9,e,COD,233,15.00,0.100,1.55,58.45
469,1091122418320,2001827036,1.60,b,Forward charges,117.9,e,COD,470,23.50,0.165,1.55,58.45
470,1091122418320,2001827036,1.60,b,Forward charges,117.9,e,COD,233,15.00,0.350,1.55,58.45
471,1091122418320,2001827036,1.60,b,Forward charges,117.9,e,COD,659,32.95,0.500,1.55,58.45
473,1091122418320,2001827036,1.60,b,Forward charges,117.9,e,COD,1140,57.00,0.137,1.55,58.45
474,1091122418320,2001827036,1.60,b,Forward charges,117.9,e,COD,350,17.50,0.010,1.55,58.45
498,1091117436652,2001808585,0.72,b,Forward charges,61.3,e,COD,233,15.00,0.127,1.55,58.45
499,1091117436652,2001808585,0.72,b,Forward charges,61.3,e,COD,563,28.15,0.240,1.55,58.45
500,1091117436652,2001808585,0.72,b,Forward charges,61.3,e,COD,286,15.00,0.133,1.55,58.45

In [41]:
data_Xslab = pd.concat([Xzone_d , Xzone_b , Xzone_e])

In [42]:
data_Xslab.shape

(398, 13)

In [43]:
data_Xslab.head()

,AWB Code,Order ID,Total weight as per Courier Company (KG),Delivery Zone charged by Courier Company,Type of Shipment,Charges Billed by Courier Company (Rs.),Delivery Zone as per X,Payment Mode,Total Order Price (rs.),COD Charge (Rs.),Total weight as per X (KG),Weight slab as per X (KG),Expected Charge as per X (Rs.)
0,1091117222124,2001806232,1.3,d,Forward charges,140.0,d,COD,932,46.60,0.240,1.25,45.4
1,1091117222124,2001806232,1.3,d,Forward charges,140.0,d,COD,10038,501.90,0.137,1.25,45.4
2,1091117222194,2001806273,1.0,d,Forward charges,101.2,d,COD,233,15.00,0.127,1.25,45.4
3,1091117222194,2001806273,1.0,d,Forward charges,101.2,d,COD,563,28.15,0.240,1.25,45.4
4,1091117222194,2001806273,1.0,d,Forward charges,101.2,d,COD,286,15.00,0.133,1.25,45.4

In [44]:
data_Xslab["Delivery Zone charged by Courier Company"].unique()

array(['d', 'b', 'e'], dtype=object)

# Calculating Weight slab as per courier company, according to different zone.

In [45]:
cou_b = data_Xslab[data_Xslab["Delivery Zone charged by Courier Company"] == 'b']
cou_b.shape

(85, 13)

In [46]:
cou_d = data_Xslab[data_Xslab["Delivery Zone charged by Courier Company"] == 'd']
cou_d.shape

(308, 13)

In [47]:
cou_e = data_Xslab[data_Xslab["Delivery Zone charged by Courier Company"] == 'e']
cou_e.shape

(5, 13)

In [48]:
def weight_slab(weight):
    i = round(weight % 1, 1)
    if i == 0.0:
        return weight
    elif i > 0.5:
        return int(weight)+1
    else:
        return int(weight)+0.5
    
cou_b["Weight slab charged by Courier Company (KG)"] = cou_b["Total weight as per Courier Company (KG)"].apply(weight_slab)
cou_b.head()

C:\Users\kusha\AppData\Local\Temp\ipykernel_9592\4035216547.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cou_b["Weight slab charged by Courier Company (KG)"] = cou_b["Total weight as per Courier Company (KG)"].apply(weight_slab)

,AWB Code,Order ID,Total weight as per Courier Company (KG),Delivery Zone charged by Courier Company,Type of Shipment,Charges Billed by Courier Company (Rs.),Delivery Zone as per X,Payment Mode,Total Order Price (rs.),COD Charge (Rs.),Total weight as per X (KG),Weight slab as per X (KG),Expected Charge as per X (Rs.),Weight slab charged by Courier Company (KG)
10,1091117223244,2001806458,1.00,b,Forward charges,61.3,b,Prepaid,626,0.0,0.35,0.5,33.0,1.0
11,1091117223244,2001806458,1.00,b,Forward charges,61.3,b,Prepaid,865,0.0,0.35,0.5,33.0,1.0
14,1091117229776,2001806885,1.00,b,Forward charges,61.3,b,COD,3840,192.0,0.21,0.5,33.0,1.0
16,1091117323112,2001807058,1.15,b,Forward charges,89.6,b,Prepaid,233,0.0,0.29,0.5,33.0,1.5
17,1091117323112,2001807058,1.15,b,Forward charges,89.6,b,Prepaid,222,0.0,0.29,0.5,33.0,1.5

In [49]:
def weight_slab(weight):
    i = round(weight % 1.25, 2)
    if i == 0.00:
        return weight
    elif weight<1.25:
        return 1.25 
    else: 
        return (weight//1.25)*1.25+1.25
cou_d["Weight slab charged by Courier Company (KG)"] = cou_d["Total weight as per Courier Company (KG)"].apply(weight_slab)
cou_d.head()

C:\Users\kusha\AppData\Local\Temp\ipykernel_9592\3263623299.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cou_d["Weight slab charged by Courier Company (KG)"] = cou_d["Total weight as per Courier Company (KG)"].apply(weight_slab)

,AWB Code,Order ID,Total weight as per Courier Company (KG),Delivery Zone charged by Courier Company,Type of Shipment,Charges Billed by Courier Company (Rs.),Delivery Zone as per X,Payment Mode,Total Order Price (rs.),COD Charge (Rs.),Total weight as per X (KG),Weight slab as per X (KG),Expected Charge as per X (Rs.),Weight slab charged by Courier Company (KG)
0,1091117222124,2001806232,1.3,d,Forward charges,140.0,d,COD,932,46.60,0.240,1.25,45.4,2.50
1,1091117222124,2001806232,1.3,d,Forward charges,140.0,d,COD,10038,501.90,0.137,1.25,45.4,2.50
2,1091117222194,2001806273,1.0,d,Forward charges,101.2,d,COD,233,15.00,0.127,1.25,45.4,1.25
3,1091117222194,2001806273,1.0,d,Forward charges,101.2,d,COD,563,28.15,0.240,1.25,45.4,1.25
4,1091117222194,2001806273,1.0,d,Forward charges,101.2,d,COD,286,15.00,0.133,1.25,45.4,1.25

In [50]:
def weight_slab(weight):
    i = round(weight % 1.5, 2)
    if i == 0.00:
        return weight
    elif weight<1.5:
        return 1.5 
    else: 
        return (weight//1.5)*1.5+1.5
    
cou_e["Weight slab charged by Courier Company (KG)"] = cou_e["Total weight as per Courier Company (KG)"].apply(weight_slab)
cou_e.head()

C:\Users\kusha\AppData\Local\Temp\ipykernel_9592\427662423.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cou_e["Weight slab charged by Courier Company (KG)"] = cou_e["Total weight as per Courier Company (KG)"].apply(weight_slab)

,AWB Code,Order ID,Total weight as per Courier Company (KG),Delivery Zone charged by Courier Company,Type of Shipment,Charges Billed by Courier Company (Rs.),Delivery Zone as per X,Payment Mode,Total Order Price (rs.),COD Charge (Rs.),Total weight as per X (KG),Weight slab as per X (KG),Expected Charge as per X (Rs.),Weight slab charged by Courier Company (KG)
64,1091117435661,2001808295,0.2,e,Forward and RTO charges,127.3,e,COD,810,40.50,0.115,1.55,111.0,1.5
65,1091117435661,2001808295,0.2,e,Forward and RTO charges,127.3,e,COD,676,33.80,0.130,1.55,111.0,1.5
88,1091120014461,2001818390,0.8,e,Forward and RTO charges,213.5,e,COD,999,49.95,0.121,1.55,111.0,1.5
89,1091120014461,2001818390,0.8,e,Forward and RTO charges,213.5,e,COD,233,15.00,0.240,1.55,111.0,1.5
90,1091120014461,2001818390,0.8,e,Forward and RTO charges,213.5,e,COD,3728,186.40,0.120,1.55,111.0,1.5

In [51]:
final = pd.concat([cou_b , cou_d , cou_e])

In [52]:
final

,AWB Code,Order ID,Total weight as per Courier Company (KG),Delivery Zone charged by Courier Company,Type of Shipment,Charges Billed by Courier Company (Rs.),Delivery Zone as per X,Payment Mode,Total Order Price (rs.),COD Charge (Rs.),Total weight as per X (KG),Weight slab as per X (KG),Expected Charge as per X (Rs.),Weight slab charged by Courier Company (KG)
10,1091117223244,2001806458,1.00,b,Forward charges,61.3,b,Prepaid,626,0.00,0.350,0.50,33.0,1.0
11,1091117223244,2001806458,1.00,b,Forward charges,61.3,b,Prepaid,865,0.00,0.350,0.50,33.0,1.0
14,1091117229776,2001806885,1.00,b,Forward charges,61.3,b,COD,3840,192.00,0.210,0.50,33.0,1.0
16,1091117323112,2001807058,1.15,b,Forward charges,89.6,b,Prepaid,233,0.00,0.290,0.50,33.0,1.5
17,1091117323112,2001807058,1.15,b,Forward charges,89.6,b,Prepaid,222,0.00,0.290,0.50,33.0,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,1091117435661,2001808295,0.20,e,Forward and RTO charges,127.3,e,COD,810,40.50,0.115,1.55,111.0,1.5
65,1091117435661,2001808295,0.20,e,Forward and RTO charges,127.3,e,COD,676,33.80,0.130,1.55,111.0,1.5
88,1091120014461,2001818390,0.80,e,Forward and RTO charges,213.5,e,COD,999,49.95,0.121,1.55,111.0,1.5
89,1091120014461,2001818390,0.80,e,Forward and RTO charges,213.5,e,COD,233,15.00,0.240,1.55,111.0,1.5
90,1091120014461,2001818390,0.80,e,Forward and RTO charges,213.5,e,COD,3728,186.40,0.120,1.55,111.0,1.5

# Total Expected Charge as per X including COD charge.

In [53]:
final["Expected Charge as per X (Rs.)"] = final["Expected Charge as per X (Rs.)"]+final["COD Charge (Rs.)"]

In [54]:
final

,AWB Code,Order ID,Total weight as per Courier Company (KG),Delivery Zone charged by Courier Company,Type of Shipment,Charges Billed by Courier Company (Rs.),Delivery Zone as per X,Payment Mode,Total Order Price (rs.),COD Charge (Rs.),Total weight as per X (KG),Weight slab as per X (KG),Expected Charge as per X (Rs.),Weight slab charged by Courier Company (KG)
10,1091117223244,2001806458,1.00,b,Forward charges,61.3,b,Prepaid,626,0.00,0.350,0.50,33.00,1.0
11,1091117223244,2001806458,1.00,b,Forward charges,61.3,b,Prepaid,865,0.00,0.350,0.50,33.00,1.0
14,1091117229776,2001806885,1.00,b,Forward charges,61.3,b,COD,3840,192.00,0.210,0.50,225.00,1.0
16,1091117323112,2001807058,1.15,b,Forward charges,89.6,b,Prepaid,233,0.00,0.290,0.50,33.00,1.5
17,1091117323112,2001807058,1.15,b,Forward charges,89.6,b,Prepaid,222,0.00,0.290,0.50,33.00,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,1091117435661,2001808295,0.20,e,Forward and RTO charges,127.3,e,COD,810,40.50,0.115,1.55,151.50,1.5
65,1091117435661,2001808295,0.20,e,Forward and RTO charges,127.3,e,COD,676,33.80,0.130,1.55,144.80,1.5
88,1091120014461,2001818390,0.80,e,Forward and RTO charges,213.5,e,COD,999,49.95,0.121,1.55,160.95,1.5
89,1091120014461,2001818390,0.80,e,Forward and RTO charges,213.5,e,COD,233,15.00,0.240,1.55,126.00,1.5
90,1091120014461,2001818390,0.80,e,Forward and RTO charges,213.5,e,COD,3728,186.40,0.120,1.55,297.40,1.5

# Difference Between Expected Charges and Billed Charges.

In [55]:
final["Difference Between Expected Charges and Billed Charges (Rs.)"] = final["Charges Billed by Courier Company (Rs.)"] - final["Expected Charge as per X (Rs.)"]
final

,AWB Code,Order ID,Total weight as per Courier Company (KG),Delivery Zone charged by Courier Company,Type of Shipment,Charges Billed by Courier Company (Rs.),Delivery Zone as per X,Payment Mode,Total Order Price (rs.),COD Charge (Rs.),Total weight as per X (KG),Weight slab as per X (KG),Expected Charge as per X (Rs.),Weight slab charged by Courier Company (KG),Difference Between Expected Charges and Billed Charges (Rs.)
10,1091117223244,2001806458,1.00,b,Forward charges,61.3,b,Prepaid,626,0.00,0.350,0.50,33.00,1.0,28.30
11,1091117223244,2001806458,1.00,b,Forward charges,61.3,b,Prepaid,865,0.00,0.350,0.50,33.00,1.0,28.30
14,1091117229776,2001806885,1.00,b,Forward charges,61.3,b,COD,3840,192.00,0.210,0.50,225.00,1.0,-163.70
16,1091117323112,2001807058,1.15,b,Forward charges,89.6,b,Prepaid,233,0.00,0.290,0.50,33.00,1.5,56.60
17,1091117323112,2001807058,1.15,b,Forward charges,89.6,b,Prepaid,222,0.00,0.290,0.50,33.00,1.5,56.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,1091117435661,2001808295,0.20,e,Forward and RTO charges,127.3,e,COD,810,40.50,0.115,1.55,151.50,1.5,-24.20
65,1091117435661,2001808295,0.20,e,Forward and RTO charges,127.3,e,COD,676,33.80,0.130,1.55,144.80,1.5,-17.50
88,1091120014461,2001818390,0.80,e,Forward and RTO charges,213.5,e,COD,999,49.95,0.121,1.55,160.95,1.5,52.55
89,1091120014461,2001818390,0.80,e,Forward and RTO charges,213.5,e,COD,233,15.00,0.240,1.55,126.00,1.5,87.50
90,1091120014461,2001818390,0.80,e,Forward and RTO charges,213.5,e,COD,3728,186.40,0.120,1.55,297.40,1.5,-83.90

In [56]:
final = final.drop(columns=["Type of Shipment" , "Payment Mode" , "Total Order Price (rs.)" , "COD Charge (Rs.)"])
final

,AWB Code,Order ID,Total weight as per Courier Company (KG),Delivery Zone charged by Courier Company,Charges Billed by Courier Company (Rs.),Delivery Zone as per X,Total weight as per X (KG),Weight slab as per X (KG),Expected Charge as per X (Rs.),Weight slab charged by Courier Company (KG),Difference Between Expected Charges and Billed Charges (Rs.)
10,1091117223244,2001806458,1.00,b,61.3,b,0.350,0.50,33.00,1.0,28.30
11,1091117223244,2001806458,1.00,b,61.3,b,0.350,0.50,33.00,1.0,28.30
14,1091117229776,2001806885,1.00,b,61.3,b,0.210,0.50,225.00,1.0,-163.70
16,1091117323112,2001807058,1.15,b,89.6,b,0.290,0.50,33.00,1.5,56.60
17,1091117323112,2001807058,1.15,b,89.6,b,0.290,0.50,33.00,1.5,56.60
...,...,...,...,...,...,...,...,...,...,...,...
64,1091117435661,2001808295,0.20,e,127.3,e,0.115,1.55,151.50,1.5,-24.20
65,1091117435661,2001808295,0.20,e,127.3,e,0.130,1.55,144.80,1.5,-17.50
88,1091120014461,2001818390,0.80,e,213.5,e,0.121,1.55,160.95,1.5,52.55
89,1091120014461,2001818390,0.80,e,213.5,e,0.240,1.55,126.00,1.5,87.50
90,1091120014461,2001818390,0.80,e,213.5,e,0.120,1.55,297.40,1.5,-83.90

In [57]:
final.reset_index(drop=True, inplace=True)

In [58]:
#Rearranging coloumn order

final = final.iloc[:, [0,1,6,7,2,9,5,3,8,4,10]]
final

,AWB Code,Order ID,Total weight as per X (KG),Weight slab as per X (KG),Total weight as per Courier Company (KG),Weight slab charged by Courier Company (KG),Delivery Zone as per X,Delivery Zone charged by Courier Company,Expected Charge as per X (Rs.),Charges Billed by Courier Company (Rs.),Difference Between Expected Charges and Billed Charges (Rs.)
0,1091117223244,2001806458,0.350,0.50,1.00,1.0,b,b,33.00,61.3,28.30
1,1091117223244,2001806458,0.350,0.50,1.00,1.0,b,b,33.00,61.3,28.30
2,1091117229776,2001806885,0.210,0.50,1.00,1.0,b,b,225.00,61.3,-163.70
3,1091117323112,2001807058,0.290,0.50,1.15,1.5,b,b,33.00,89.6,56.60
4,1091117323112,2001807058,0.290,0.50,1.15,1.5,b,b,33.00,89.6,56.60
...,...,...,...,...,...,...,...,...,...,...,...
393,1091117435661,2001808295,0.115,1.55,0.20,1.5,e,e,151.50,127.3,-24.20
394,1091117435661,2001808295,0.130,1.55,0.20,1.5,e,e,144.80,127.3,-17.50
395,1091120014461,2001818390,0.121,1.55,0.80,1.5,e,e,160.95,213.5,52.55
396,1091120014461,2001818390,0.240,1.55,0.80,1.5,e,e,126.00,213.5,87.50
397,1091120014461,2001818390,0.120,1.55,0.80,1.5,e,e,297.40,213.5,-83.90

# Creating Summary Table.

In [59]:
# Calculate the total orders in each category
total_correctly_charged = len(final[final['Difference Between Expected Charges and Billed Charges (Rs.)'] == 0])
total_overcharged = len(final[final['Difference Between Expected Charges and Billed Charges (Rs.)'] > 0])
total_undercharged = len(final[final['Difference Between Expected Charges and Billed Charges (Rs.)'] < 0])

# Calculate the total amount in each category
amount_overcharged = abs(final[final['Difference Between Expected Charges and Billed Charges (Rs.)'] > 0]['Difference Between Expected Charges and Billed Charges (Rs.)'].sum())
amount_undercharged = final[final['Difference Between Expected Charges and Billed Charges (Rs.)'] < 0]['Difference Between Expected Charges and Billed Charges (Rs.)'].sum()
amount_correctly_charged = final[final['Difference Between Expected Charges and Billed Charges (Rs.)'] == 0]['Expected Charge as per X (Rs.)'].sum()

# Create a new DataFrame for the summary
summary_data = {'Description': ['Total Orders where X has been correctly charged',
                                'Total Orders where X has been overcharged',
                                'Total Orders where X has been undercharged'],
                'Count': [total_correctly_charged, total_overcharged, total_undercharged],
                'Amount (Rs.)': [amount_correctly_charged, amount_overcharged, amount_undercharged]}

df_summary = pd.DataFrame(summary_data)

print(df_summary)

                                       Description  Count  Amount (Rs.)
0  Total Orders where X has been correctly charged     11        462.20
1        Total Orders where X has been overcharged    347      26797.90
2       Total Orders where X has been undercharged     40      -7105.85

# Conclusion : Total amount where X is overcharged is Rs. 19692.9.

#Exporting data to workbook

In [60]:
with pd.ExcelWriter("K:\Major project\cointab\Assignment details\processed files\\Cointab_DA_assignment.xlsx") as writer:
    final.to_excel(writer, sheet_name='Output Data 1', index=False)
    df_summary.to_excel(writer, sheet_name='Output Data 2', index=False)